# Generated by Django 5.2.7 on 2025-10-18 11:17

import charidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=charidfield.fields.CharIDField(default='o0bn6uhkh9n7hmh5hdfokh9n', editable=False, max_length=30, prefix='usr_', primary_key=True, serialize=False, unique=True),
        ),
    ]
