# Generated by Django 5.2.7 on 2025-10-18 11:54

import charidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=charidfield.fields.CharIDField(default='anyc8vds9hfh7adym7gaf9mi', editable=False, max_length=30, prefix='usr_', primary_key=True, serialize=False, unique=True),
        ),
    ]
